line.bot:
  channel-token: <your token>
  channel-secret: <your secret>
  handler.path: /callback


image: https://imgur.com/zwY6PHr.jpg
pre: https://imgur.com/COoddgs.jpg

#image: https://lh3.googleusercontent.com/9iPV-Xr0NpwMiKFqjGxReVwq95OxGJKWgqbXBsU8OPwgdNuCA727YnosYd02EIrR8Cd7ubQy2aX_OpRKvYg0lIjbxc7jETzgW8UMw0DrIP1skoOsCYCOKeGyzBCs9kVXAhhgrPKT5UP8bkbLG9azj99AZz5BxRMVPe_l-09aacweXp5NiWV_If-qGQXPTS6dLKhySFqVdZOUX_AUc0mpkUEcp2ikrzfBIW804qexANDNqO4LohdFJcEvuNhTjxPE8HAAIwAY-7qxeaOQf67ozCXIJHzUvG_Jx2Ku5a_uWEdWAsJoGsQlchrGBT7MNw2bxzVG4M2_sUPPRLTvQqmm2MJn0gW1PBFAso4LfMMck3U-xGMe2lS8l5TgzKGT1sPqujGmgDygqD4zg8xiGn1mrlCr57ugAJxFzBrsMuP2lwSrp_K9LHGo-oCRkfC5ZbmrVDLJCdp4XTfOd2-XiLsV28GIpA9F5I-zjq_1Nr7jBsqDchHfuszhFLWfSDU9rzxxWlxvs1TSh_5nqnA2Uh-H94jtBVUHvh9i1iSlxJn7n26k1-3kXamh5gSnfaSFFgzDCu_30Kmx7xpCyMW_IvZ49UANsCh0Sv2N8qHg8SwGGD8y2m8vcAcMEQEgIGE5rfhD9htFR5-N5UmXfYz8q5DpwolCi-moJbKq7PaQDB4_Fn33ireWEBsS0IU=w545-h867-no
#pre: https://lh3.googleusercontent.com/m2IJVzER58YCGb9gpw0LFhOYxEPRo472dAL9S2rz-X5Y3CN3q4kvtWzl_ZAikjAQS_UlcgvwVzepJKZhL1vvcEA6lvZAUphYUpkUqQf_xY1s7Km9eoG9y5dLe7LV0YBCjpY6FqPCu97CvI1LcIbR07eHjQleXPSmZxPyUNUGen6LKgt45pc4uWmM02RSi549PDyjeG8HarxhC8G3nz4yD_P-1YJ3HjFYdXAmMxgcUhbY-G5JyEM1AWRZCvEGeO5Y76MIWNUMJ537CeQKJ3Me3SBlOujs4oE4udfDm0_NPgXH26ocUc_qVRTPd3wqpDoa-pnNlUrlrfxguALxPlSx1v0EcHcK5IZ9dPhcnny7A82YXfv-qr9QCyKQtEgMMTMctvHOrZOGfeaH0IXq59QIbkteONxDXTe5D3mEoMVKeikJn9wzrbj20F6v-_3ct2CK3eCD3Ku8G8emYxBZYxLx8DHaBu91HoPQm-7_SV3dLt8R2BarN7IK82w0W411KokZp9mSF1sZhnimDJ46WTLKUT2bamt3g2gQHMPqiWXf6insAH6XRsOf924YWPcl7GJNhWh0WVuLKldp3yFihkPZynWuw5A5THJFgLag9lqiyMnkh8EJC1zhWNfcpBUhj9qwoDEMC5dOynGtyIfodWcyhHc_YYkCzm8QDlDwxU5zrhm7905RuUrLnek=w150-h240-no

sendto: Ub0bdbb347e2432d9dc8d9eb91d859067

# Ccb594be9aeab03a635f77d5464918a94 //小夥伴
# C16d561b602896ef1d859bdb0a3094bc0 //南1
# Ce1372076effeac87b01cd1867c72a685 //兩人