line.bot:
  channel-token: <your token>
  channel-secret: <your secret>
  handler.path: /callback

picyamUrl: https://raw.githubusercontent.com/eason771108/taitra-linebot/master/morningCall/src/main/resources/pic.yml
sendto: Ub0bdbb347e2432d9dc8d9eb91d859067

# Ccb594be9aeab03a635f77d5464918a94 //小夥伴
# C16d561b602896ef1d859bdb0a3094bc0 //南1
# Ce1372076effeac87b01cd1867c72a685 //兩人